### ISSUE TITLE
Codemod for v8 -> v9 rule API changes

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint-transforms#25]
We should create a codemod that applies most of the changes [mentioned in the blog post](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/) about changes to the rule API. Primarily changing:

* `context.getScope()`
* `context.markVariableAsUsed()`
* `context.getAncestors()`
* `context.getDeclaredVariables()`

For each of these, we should be creating backwards-compatible code such as:

```js
const sourceCode = context.sourceCode ?? context.getSourceCode();
const cwd = context.cwd ?? context.getCwd();
const filename = context.filename ?? context.getFilename();
const physicalFilename = context.physicalFilename ?? context.getPhysicalFilename();
```

We should also update references to the methods listed in [this section](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#from-context-to-sourcecode)

If we find a reference to `CodePath#currentSegments`, then the best thing to do is output a warning stating that it can't be fixed automatically and point to [this section](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#codepath%23currentsegments).

(It probably can be fixed automatically but would be pretty complicated. If we get enough requests then we can revisit.)

**Comment by mdjermanovic** [comment]
I'm wondering if we need this project anymore, because `eslint` + `eslint-plugin-eslint-plugin` could be able to do the same.

https://github.com/eslint-community/eslint-plugin-eslint-plugin/issues/398

**Comment by nzakas** [comment]
Maybe, but creating a dependency on ESLint in order to fix plugins that aren't working in ESLint might cause issues. I think updating this tool to have something standalone is beneficial at least in the near term.

**Comment by mdjermanovic** [comment]
`eslint` and `eslint-plugin-eslint-plugin` would only be dev dependencies. I believe most if not all plugins already have `eslint` as a dev dependency, and a lot of plugins already use `eslint-plugin-eslint-plugin` (and eslint plugins should generally be using `eslint-plugin-eslint-plugin` anyway). In any case, they could use them as a one-time tool to fix the code and then uninstall them.

But okay, I'm not opposed to updating this tool as well.

**Comment by snitin315** [comment]
> We should also update references to the methods listed in [this section](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#from-context-to-sourcecode)

How should we handle `context.getComments()`  in the codemod? Since `SourceCode.getComments()` was removed in v9. Should we just log a warning and [link to docs](https://eslint.org/docs/latest/use/migrate-to-9.0.0#removed-sourcecode-getcomments)?
<img width="699" alt="Screenshot 2024-05-21 at 9 27 56 PM" src="https://github.com/eslint/eslint-transforms/assets/46647141/75ccab4d-2bbb-4d1d-bb9e-ee020b34df38">
